modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Core/issues"

[[mods]]
    modId="project_essentials_core"
    version="${file.jarVersion}"
    displayName="Project Essentials Core"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Core/MC-1.15.2/updatev2.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Core"
    credits="hujle, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    API for creating modules of Project Essentials and reduce code duplication,
    also core module contains kotlin runtime and libraries. Also contains some
    settings for vanilla commands and events.
    '''

[[dependencies.project_essentials_core]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
