modLoader="javafml" 
loaderVersion="[28,)" 
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Core/issues"

[[mods]] 
    modId="project_essentials_core"
    version="1.14.4-1.0.1.0"
    displayName="Project Essentials Core"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Core/MC-1.14.X/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Core"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Core API - core module for Essentials;
    Just API with common code for Project Essentials developers.
    '''

[[dependencies.projectessentialscore]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialscore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
