modLoader="javafml" 
loaderVersion="[28,)"
logoFile="logo.png"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Core/issues"

[[mods]]
    modId="project_essentials_core"
    version="2.0.0-RC.1+MC-1.14.4"
    displayName="Project Essentials Core"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Core/MC-1.14.4/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Core"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Core API - core module for Essentials;
    Just API with common code for Project Essentials developers.
    '''

[[dependencies.project_essentials_core]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
